version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 15
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
